// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoADNTzkjofuw-owZYmAl4Xu3wTqv2Hi0',
    appId: '1:888389567809:web:54b691091fdc68c0544dc0',
    messagingSenderId: '888389567809',
    projectId: 'whatsappflutter-23016',
    authDomain: 'whatsappflutter-23016.firebaseapp.com',
    storageBucket: 'whatsappflutter-23016.appspot.com',
    measurementId: 'G-3EGLW0PNQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADLe6_GU02f5a4V1lQfFcfvw-ryK5gC4w',
    appId: '1:888389567809:android:946196718bbece4c544dc0',
    messagingSenderId: '888389567809',
    projectId: 'whatsappflutter-23016',
    storageBucket: 'whatsappflutter-23016.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjpQ1gEGWCve2FfJemHYrHuhOlxrAwo7Y',
    appId: '1:888389567809:ios:0df930b088a14a12544dc0',
    messagingSenderId: '888389567809',
    projectId: 'whatsappflutter-23016',
    storageBucket: 'whatsappflutter-23016.appspot.com',
    iosBundleId: 'com.example.whats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjpQ1gEGWCve2FfJemHYrHuhOlxrAwo7Y',
    appId: '1:888389567809:ios:9777086399ed8084544dc0',
    messagingSenderId: '888389567809',
    projectId: 'whatsappflutter-23016',
    storageBucket: 'whatsappflutter-23016.appspot.com',
    iosBundleId: 'com.example.whats.RunnerTests',
  );
}
